---
root: true

env:
  browser: true
  es6: true

parser: babel-eslint

extends:
  - airbnb

rules:
  arrow-parens:
    - error
    - always
  comma-dangle:
    - error
    - never

  function-paren-newline: off
  no-restricted-globals: off
  object-curly-newline: off
  jsx-a11y/anchor-is-valid: off
  react/default-props-match-prop-types: off
  react/jsx-closing-tag-location: off

  implicit-arrow-linebreak: off
  no-else-return: off
  no-multiple-empty-lines: off
  operator-linebreak: off
  react/destructuring-assignment: off
  react/jsx-one-expression-per-line: off
  react/jsx-wrap-multilines: off
  react/no-access-state-in-setstate: off
  react/require-default-props: off
