---
root: true

env:
  browser: true
  es6: true

parser: babel-eslint

extends:
  - airbnb

rules:
  arrow-parens:
    - error
    - always
  comma-dangle:
    - error
    -
      arrays: always-multiline
      objects: always-multiline
      imports: always-multiline
      exports: always-multiline
      functions: never
  max-len: off

  jsx-a11y/anchor-is-valid: off
  jsx-a11y/media-has-caption: off

  implicit-arrow-linebreak: off
  no-multiple-empty-lines: off
  operator-linebreak: off
  react/destructuring-assignment: off
  react/no-access-state-in-setstate: off
