version: 2

sphinx:
  configuration: docs/source/conf.py

formats: all

conda:
  environment: docs/rtd_conda.yml

python:
  version: 3.6
  install:
    - requirements: docs/requirements.txt
    - requirements: requirements.txt
