version: 2

formats: all

conda:
  environment: docs/rtd_conda.yml

python:
  version: 3.6
  install:
    - method: pip
      path: .
      requirements: docs/requirements.txt
    - method: pip
      path: .

sphinx:
  configuration: docs/source/conf.py
