language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"

services:
  - docker

notifications:
  email: false

sudo: false

before_install:
  - pip install autopep8 hacking
  - pip install -U pytest pytest-cov coveralls
  - pip install Pillow matplotlib
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then pip install mock; fi
  - npm install -g npm@6
  - npm -v

install:
  - pushd frontend
  - npm install && npm run build -- --progress=false --profile=false
  - popd
  - pip install -e .

script:
  # python style check
  - flake8
  - autopep8 -r . --global-config .pep8 --diff | tee check_autopep8
  - test ! -s check_autopep8
  # frontend style check
  - pushd frontend
  - npm run lint
  - popd
  # chainerui install test
  - chainerui db create
  - chainerui db upgrade
  - chainerui server -p 5051 &
  - sleep 4
  - curl -f http://127.0.0.1:5051/
  - CHAINERUI_ENV=test pytest --cov=chainerui

after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then COVERALLS_TOKEN=$COVERALLS_TOKEN coveralls; fi

deploy:
  - provider: pypi
    user: $PYPI_MAINTAINER_NAME
    password: $PYPI_MAINTAINER_PASS
    on:
      tags: true
      python: 3.6
    allow_failure: false
    skip_cleanup: true
  - provider: script
    script: bash .travis/docker_push.sh
    on:
      tags: true
      python: 3.6
    allow_failure: false
    skip_cleanup: true
